modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

credits="Thanks go to Nudelauflauch for the textures"
authors= "${mod_authors}"

description='''
___________________
This mod adds CHEESE
___________________

'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
