modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods" #optional

[[mods]] #mandatory

modId="cheesus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cheesus" #mandatory
credits="Thanks go to NUDLAUFLAUCH and AGENT BROKKOLI 007 for all of the textures" #optional
authors="Stehschnitzel" #optional

description='''
Makes Cheese
'''


[[dependencies.cheesus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"